# =============================================================================
# Production Overrides
# =============================================================================
# docker compose -f docker-compose.yaml -f docker-compose.prod.yml up -d
# =============================================================================

services:
  stats-refresh-consumer:
    env_file:
      - .env.prod
